### ISSUE TITLE
Add YAML file to configure report system

### ISSUE THREAD

**Issue by gryckelynck** [georchestra/sdi-consistence-check#74]
Something like

``` yaml
reports:
  - mode: WMS
    server: https://public.sig.rennesmetropole.fr/geoserver/wms
    disable_ssl_verification: true
    to_file: rennes-report-wms.log
  - mode: WFS
    server: https://public.sig.rennesmetropole.fr/geoserver/wfs
    disable_ssl_verification: true
    to_file: rennes-report-wfs.log
  - mode: CSW
    server: https://public.sig.rennesmetropole.fr/geonetwork/srv/fre/csw
    disable_ssl_verification: false
    to_file: rennes-report-csw.log
```

with option `--configure FILE`
